//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_for_service_supportEntities : DbContext
    {
        public DB_for_service_supportEntities()
            : base("name=DB_for_service_supportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Модели_тренажёров> Модели_тренажёров { get; set; }
        public virtual DbSet<Подходящие_запасные_детали> Подходящие_запасные_детали { get; set; }
        public virtual DbSet<Ремонт> Ремонт { get; set; }
        public virtual DbSet<Склад_запасных_деталей> Склад_запасных_деталей { get; set; }
        public virtual DbSet<Состояние_сотрудника> Состояние_сотрудника { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Тренажёры> Тренажёры { get; set; }
        public virtual DbSet<Устанавливаемые_тренажёры> Устанавливаемые_тренажёры { get; set; }
        public virtual DbSet<Установка_тренажёров> Установка_тренажёров { get; set; }
        public virtual DbSet<Установленные_детали> Установленные_детали { get; set; }
    }
}
