//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Подходящие_запасные_детали
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Подходящие_запасные_детали()
        {
            this.Установленные_детали = new HashSet<Установленные_детали>();
        }
    
        public string Код_детали { get; set; }
        public string Начало_SN { get; set; }
    
        public virtual Модели_тренажёров Модели_тренажёров { get; set; }
        public virtual Склад_запасных_деталей Склад_запасных_деталей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Установленные_детали> Установленные_детали { get; set; }
    }
}
