//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Устанавливаемые_тренажёры
    {
        public int ID_установки { get; set; }
        public string Начало_SN { get; set; }
        public int Количество { get; set; }
    
        public virtual Модели_тренажёров Модели_тренажёров { get; set; }
        public virtual Установка_тренажёров Установка_тренажёров { get; set; }
    }
}
