//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Установленные_детали
    {
        public int ID_установки_детали { get; set; }
        public string Начало_SN { get; set; }
        public string Конец_SN { get; set; }
        public string Код_детали { get; set; }
        public int Количество { get; set; }
        public System.DateTime Дата_установки { get; set; }
        public string Примечания { get; set; }
    
        public virtual Подходящие_запасные_детали Подходящие_запасные_детали { get; set; }
        public virtual Тренажёры Тренажёры { get; set; }
    }
}
