//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Установка_тренажёров
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Установка_тренажёров()
        {
            this.Тренажёры = new HashSet<Тренажёры>();
            this.Устанавливаемые_тренажёры = new HashSet<Устанавливаемые_тренажёры>();
        }
    
        public int ID_установки { get; set; }
        public int ID_сотрудника { get; set; }
        public int Код_клиента { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_установки { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тренажёры> Тренажёры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Устанавливаемые_тренажёры> Устанавливаемые_тренажёры { get; set; }
    }
}
